In [41]:
import dimcat as dc
import pandas as pd

Load corpus:

In [3]:
corpus = dc.Corpus()
corpus.load("~/Uni/phd/data/ABC")
corpus.data

282 files.
KEY -> EXTENSIONS
-----------------
ABC -> {'.mscx': 71, '.tsv': 211}

None of the 71 score files have been parsed.

All 211 tabular files have been parsed, 70 of them as Annotations object(s).
KEY -> ANNOTATION LAYERS
------------------------
ABC -> staff  voice  harmony_layer  color
    -> 4      1      1 (dcml)       default    27362
    -> 1      1      0 (dcml)       default      731

Get chord labels:

In [89]:
labels = corpus.get_facet("expanded")
labels

                                     quarterbeats  duration_qb   mc   mn  \
corpus fname        interval
ABC    n01op18-1_01 [0.0, 3.0)                  0          3.0    1    1
                    [3.0, 6.0)                  3          3.0    2    2
                    [6.0, 9.0)                  6          3.0    3    3
                    [9.0, 15.0)                 9          6.0    4    4
                    [15.0, 18.0)               15          3.0    6    6
...                                           ...          ...  ...  ...
       n16op135_04  [1140.0, 1141.0)         1140          1.0  281  280
                    [1141.0, 1142.0)         1141          1.0  281  280
                    [1142.0, 1144.0)         1142          2.0  282  281
                    [1144.0, 1146.0)         1144          2.0  282  281
                    [1146.0, 1150.0)         1146          4.0  283  282

                                     mc_onset mn_onset timesig  staff  voice  \
corpus fname        interval
ABC    n01op18-1_01 [0.0, 3.0)              0        0     3/4      4      1
                    [3.0, 6.0)              0        0     3/4      4      1
                    [6.0, 9.0)              0        0     3/4      4      1
                    [9.0, 15.0)             0        0     3/4      4      1
                    [15.0, 18.0)            0        0     3/4      4      1
...                                       ...      ...     ...    ...    ...
       n16op135_04  [1140.0, 1141.0)      1/2      1/2     4/4      4      1
                    [1141.0, 1142.0)      3/4      3/4     4/4      4      1
                    [1142.0, 1144.0)        0        0     4/4      4      1
                    [1144.0, 1146.0)      1/2      1/2     4/4      4      1
                    [1146.0, 1150.0)        0        0     4/4      4      1

                                      volta  ... phraseend chord_type  \
corpus fname        interval                 ...
ABC    n01op18-1_01 [0.0, 3.0)         <NA>  ...       NaN          M
                    [3.0, 6.0)         <NA>  ...       NaN          M
                    [6.0, 9.0)         <NA>  ...       NaN          M
                    [9.0, 15.0)        <NA>  ...       NaN          M
                    [15.0, 18.0)       <NA>  ...       NaN        Mm7
...                                     ...  ...       ...        ...
       n16op135_04  [1140.0, 1141.0)   <NA>  ...       NaN          M
                    [1141.0, 1142.0)   <NA>  ...       NaN          M
                    [1142.0, 1144.0)   <NA>  ...       NaN          M
                    [1144.0, 1146.0)   <NA>  ...       NaN        Mm7
                    [1146.0, 1150.0)   <NA>  ...        \\          M

                                     globalkey_is_minor localkey_is_minor  \
corpus fname        interval
ABC    n01op18-1_01 [0.0, 3.0)                    False             False
                    [3.0, 6.0)                    False             False
                    [6.0, 9.0)                    False             False
                    [9.0, 15.0)                   False             False
                    [15.0, 18.0)                  False             False
...                                                 ...               ...
       n16op135_04  [1140.0, 1141.0)               True             False
                    [1141.0, 1142.0)               True             False
                    [1142.0, 1144.0)               True             False
                    [1144.0, 1146.0)               True             False
                    [1146.0, 1150.0)               True             False

                                        chord_tones added_tones root  \
corpus fname        interval
ABC    n01op18-1_01 [0.0, 3.0)            (0, 4, 1)          ()    0
                    [3.0, 6.0)            (1, 5, 2)          ()    1
                    [6.0, 9.0)            (0, 4, 1)          ()    0
                    [9.0, 15.0)          (3, 0, -1)          ()   -1
                    [15.0, 18.0)      (5, 2, -1, 1)          ()    1
...                                             ...         ...  ...
       n16op135_04  [1140.0, 1141.0)      (0, 4, 1)          ()    0
                    [1141.0, 1142.0)      (4, 1, 0)          ()    0
                    [1142.0, 1144.0)      (1, 0, 4)          ()    1
                    [1144.0, 1146.0)  (1, 5, 2, -1)          ()    1
                    [1146.0, 1150.0)      (0, 4, 1)          ()    0

                                     bass_note alt_label pedalend
corpus fname        interval
ABC    n01op18-1_01 [0.0, 3.0)               0       NaN      NaN
                    [3.0, 6.0)               1       NaN      NaN
                    [6.0, 9.0)               0       NaN      NaN
                    [9.0, 15.0)              3       NaN      NaN
                    [15.0, 18.0)             5       NaN      NaN
...                                        ...       ...      ...
       n16op135_04  [1140.0, 1141.0)         0       NaN      NaN
                    [1141.0, 1142.0)         4       NaN      NaN
                    [1142.0, 1144.0)         1       NaN      NaN
                    [1144.0, 1146.0)         1       NaN      NaN
                    [1146.0, 1150.0)         0       NaN      NaN

[27960 rows x 34 columns]

Get segments:

In [17]:
chord_slices = dc.ChordFeatureSlicer().process_data(corpus)

/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))

/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))

/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:923: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  grouped = df.groupby(list(groups), dropna=False).apply(reduce_dataframe_duration_to_first_row)
DEBUG:ABC_n14op131_06:Groupby-apply did not generate MultiIndex.
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))
/home/chfin/dateien/dev/python/dimcat-test/env/lib/python3.10/site-packages/ms3/transformations.py:921: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  *(adjacency_groups(c, na_values=na) for (_, c), na in zip(df[cols].iteritems(), na_values)))

In [23]:
sliced_notes = chord_slices.get_facet("notes")
sliced_notes

                                                      quarterbeats  \
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)                  0
                                     [0.0, 1.0)                  0
                                     [0.0, 1.0)                  0
                                     [0.0, 1.0)                  0
                                     [1.0, 1.5)                  1
...                                                            ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)         1146
                                     [1146.0, 1147.0)         1146
                                     [1146.0, 1147.0)         1146
                                     [1146.0, 1147.0)         1146
                                     [1146.0, 1147.0)         1146

                                                       duration_qb   mc   mn  \
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)                1.0    1    1
                                     [0.0, 1.0)                1.0    1    1
                                     [0.0, 1.0)                1.0    1    1
                                     [0.0, 1.0)                1.0    1    1
                                     [1.0, 1.5)                0.5    1    1
...                                                            ...  ...  ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)          1.0  283  282
                                     [1146.0, 1147.0)          1.0  283  282
                                     [1146.0, 1147.0)          1.0  283  282
                                     [1146.0, 1147.0)          1.0  283  282
                                     [1146.0, 1147.0)          1.0  283  282

                                                      mc_onset mn_onset  \
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)              0        0
                                     [0.0, 1.0)              0        0
                                     [0.0, 1.0)              0        0
                                     [0.0, 1.0)              0        0
                                     [1.0, 1.5)            1/4      1/4
...                                                        ...      ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)        0        0
                                     [1146.0, 1147.0)        0        0
                                     [1146.0, 1147.0)        0        0
                                     [1146.0, 1147.0)        0        0
                                     [1146.0, 1147.0)        0        0

                                                      timesig  staff  voice  \
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)           3/4      3      1
                                     [0.0, 1.0)           3/4      4      1
                                     [0.0, 1.0)           3/4      1      1
                                     [0.0, 1.0)           3/4      2      1
                                     [1.0, 1.5)           3/4      3      1
...                                                       ...    ...    ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)     4/4      3      1
                                     [1146.0, 1147.0)     4/4      1      1
                                     [1146.0, 1147.0)     4/4      2      1
                                     [1146.0, 1147.0)     4/4      2      1
                                     [1146.0, 1147.0)     4/4      1      1

                                                      duration gracenote  \
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)            1/4       NaN
                                     [0.0, 1.0)            1/4       NaN
                                     [0.0, 1.0)            1/4       NaN
                                     [0.0, 1.0)            1/4       NaN
                                     [1.0, 1.5)            1/8       NaN
...                                                        ...       ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)      1/4       NaN
                                     [1146.0, 1147.0)      1/4       NaN
                                     [1146.0, 1147.0)      1/4       NaN
                                     [1146.0, 1147.0)      1/4       NaN
                                     [1146.0, 1147.0)      1/4       NaN

                                                      nominal_duration scalar  \
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)                    1/4      1
                                     [0.0, 1.0)                    1/4      1
                                     [0.0, 1.0)                    1/4      1
                                     [0.0, 1.0)                    1/4      1
                                     [1.0, 1.5)                    1/8      1
...                                                                ...    ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)              1/4      1
                                     [1146.0, 1147.0)              1/4      1
                                     [1146.0, 1147.0)              1/4      1
                                     [1146.0, 1147.0)              1/4      1
                                     [1146.0, 1147.0)              1/4      1

                                                       tied  tpc  midi  volta  \
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)           1   -1    53   <NA>
                                     [0.0, 1.0)           1   -1    53   <NA>
                                     [0.0, 1.0)           1   -1    65   <NA>
                                     [0.0, 1.0)           1   -1    65   <NA>
                                     [1.0, 1.5)          -1   -1    53   <NA>
...                                                     ...  ...   ...    ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)  <NA>   -1    53   <NA>
                                     [1146.0, 1147.0)  <NA>    3    69   <NA>
                                     [1146.0, 1147.0)  <NA>    3    69   <NA>
                                     [1146.0, 1147.0)  <NA>   -1    77   <NA>
                                     [1146.0, 1147.0)  <NA>   -1    89   <NA>

                                                       chord_id tremolo
corpus fname        chord_slice      interval
ABC    n01op18-1_01 [0.0, 3.0)       [0.0, 1.0)              12     NaN
                                     [0.0, 1.0)              18     NaN
                                     [0.0, 1.0)               0     NaN
                                     [0.0, 1.0)               6     NaN
                                     [1.0, 1.5)              13     NaN
...                                                         ...     ...
       n16op135_04  [1146.0, 1150.0) [1146.0, 1147.0)      2731     NaN
                                     [1146.0, 1147.0)      2729     NaN
                                     [1146.0, 1147.0)      2730     NaN
                                     [1146.0, 1147.0)      2730     NaN
                                     [1146.0, 1147.0)      2729     NaN

[245901 rows x 19 columns]

In [22]:
chord_slices.get_slice_info()

                                     quarterbeats duration_qb   mc   mn  \
corpus fname        chord_slice
ABC    n01op18-1_01 [0.0, 3.0)                  0         3.0    1    1
                    [3.0, 6.0)                  3         3.0    2    2
                    [6.0, 9.0)                  6         3.0    3    3
                    [9.0, 15.0)                 9         6.0    4    4
                    [15.0, 18.0)               15         3.0    6    6
...                                           ...         ...  ...  ...
       n16op135_04  [1140.0, 1141.0)         1140         1.0  281  280
                    [1141.0, 1142.0)         1141         1.0  281  280
                    [1142.0, 1144.0)         1142         2.0  282  281
                    [1144.0, 1146.0)         1144         2.0  282  281
                    [1146.0, 1150.0)         1146         4.0  283  282

                                     mc_onset mn_onset timesig staff voice  \
corpus fname        chord_slice
ABC    n01op18-1_01 [0.0, 3.0)              0        0     3/4     4     1
                    [3.0, 6.0)              0        0     3/4     4     1
                    [6.0, 9.0)              0        0     3/4     4     1
                    [9.0, 15.0)             0        0     3/4     4     1
                    [15.0, 18.0)            0        0     3/4     4     1
...                                       ...      ...     ...   ...   ...
       n16op135_04  [1140.0, 1141.0)      1/2      1/2     4/4     4     1
                    [1141.0, 1142.0)      3/4      3/4     4/4     4     1
                    [1142.0, 1144.0)        0        0     4/4     4     1
                    [1144.0, 1146.0)      1/2      1/2     4/4     4     1
                    [1146.0, 1150.0)        0        0     4/4     4     1

                                     volta  ... phraseend chord_type  \
corpus fname        chord_slice             ...
ABC    n01op18-1_01 [0.0, 3.0)        <NA>  ...       NaN          M
                    [3.0, 6.0)        <NA>  ...       NaN          M
                    [6.0, 9.0)        <NA>  ...       NaN          M
                    [9.0, 15.0)       <NA>  ...       NaN          M
                    [15.0, 18.0)      <NA>  ...       NaN        Mm7
...                                    ...  ...       ...        ...
       n16op135_04  [1140.0, 1141.0)  <NA>  ...       NaN          M
                    [1141.0, 1142.0)  <NA>  ...       NaN          M
                    [1142.0, 1144.0)  <NA>  ...       NaN          M
                    [1144.0, 1146.0)  <NA>  ...       NaN        Mm7
                    [1146.0, 1150.0)  <NA>  ...        \\          M

                                     globalkey_is_minor localkey_is_minor  \
corpus fname        chord_slice
ABC    n01op18-1_01 [0.0, 3.0)                    False             False
                    [3.0, 6.0)                    False             False
                    [6.0, 9.0)                    False             False
                    [9.0, 15.0)                   False             False
                    [15.0, 18.0)                  False             False
...                                                 ...               ...
       n16op135_04  [1140.0, 1141.0)               True             False
                    [1141.0, 1142.0)               True             False
                    [1142.0, 1144.0)               True             False
                    [1144.0, 1146.0)               True             False
                    [1146.0, 1150.0)               True             False

                                        chord_tones added_tones root  \
corpus fname        chord_slice
ABC    n01op18-1_01 [0.0, 3.0)            (0, 4, 1)          ()    0
                    [3.0, 6.0)            (1, 5, 2)          ()    1
                    [6.0, 9.0)            (0, 4, 1)          ()    0
                    [9.0, 15.0)          (3, 0, -1)          ()   -1
                    [15.0, 18.0)      (5, 2, -1, 1)          ()    1
...                                             ...         ...  ...
       n16op135_04  [1140.0, 1141.0)      (0, 4, 1)          ()    0
                    [1141.0, 1142.0)      (4, 1, 0)          ()    0
                    [1142.0, 1144.0)      (1, 0, 4)          ()    1
                    [1144.0, 1146.0)  (1, 5, 2, -1)          ()    1
                    [1146.0, 1150.0)      (0, 4, 1)          ()    0

                                     bass_note alt_label pedalend
corpus fname        chord_slice
ABC    n01op18-1_01 [0.0, 3.0)               0       NaN      NaN
                    [3.0, 6.0)               1       NaN      NaN
                    [6.0, 9.0)               0       NaN      NaN
                    [9.0, 15.0)              3       NaN      NaN
                    [15.0, 18.0)             5       NaN      NaN
...                                        ...       ...      ...
       n16op135_04  [1140.0, 1141.0)         0       NaN      NaN
                    [1141.0, 1142.0)         4       NaN      NaN
                    [1142.0, 1144.0)         1       NaN      NaN
                    [1144.0, 1146.0)         1       NaN      NaN
                    [1146.0, 1150.0)         0       NaN      NaN

[27340 rows x 34 columns]

In [28]:
salami = dc.NoteSlicer().process_data(corpus)

In [32]:
salami_notes = salami.get_facet("notes")

In [50]:
salami_notes.loc[("ABC", "n01op18-1_01")]

                              quarterbeats  duration_qb   mc   mn mc_onset  \
onset_slice    interval
[0.0, 1.0)     [0.0, 1.0)                0          1.0    1    1        0
               [0.0, 1.0)                0          1.0    1    1        0
               [0.0, 1.0)                0          1.0    1    1        0
               [0.0, 1.0)                0          1.0    1    1        0
[1.0, 1.5)     [1.0, 1.5)                1          0.5    1    1      1/4
...                                    ...          ...  ...  ...      ...
[937.0, 938.0) [937.0, 938.0)          937          1.0  313  313      1/4
               [937.0, 938.0)          937          1.0  313  313      1/4
               [937.0, 938.0)          937          1.0  313  313      1/4
               [937.0, 938.0)          937          1.0  313  313      1/4
               [937.0, 938.0)          937          1.0  313  313      1/4

                              mn_onset timesig  staff  voice duration  \
onset_slice    interval
[0.0, 1.0)     [0.0, 1.0)            0     3/4      3      1      1/4
               [0.0, 1.0)            0     3/4      4      1      1/4
               [0.0, 1.0)            0     3/4      1      1      1/4
               [0.0, 1.0)            0     3/4      2      1      1/4
[1.0, 1.5)     [1.0, 1.5)          1/4     3/4      3      1      1/8
...                                ...     ...    ...    ...      ...
[937.0, 938.0) [937.0, 938.0)      1/4     3/4      3      1      1/4
               [937.0, 938.0)      1/4     3/4      2      1      1/4
               [937.0, 938.0)      1/4     3/4      2      1      1/4
               [937.0, 938.0)      1/4     3/4      1      1      1/4
               [937.0, 938.0)      1/4     3/4      1      1      1/4

                              gracenote nominal_duration scalar  tied  tpc  \
onset_slice    interval
[0.0, 1.0)     [0.0, 1.0)           NaN              1/4      1     1   -1
               [0.0, 1.0)           NaN              1/4      1     1   -1
               [0.0, 1.0)           NaN              1/4      1     1   -1
               [0.0, 1.0)           NaN              1/4      1     1   -1
[1.0, 1.5)     [1.0, 1.5)           NaN              1/8      1    -1   -1
...                                 ...              ...    ...   ...  ...
[937.0, 938.0) [937.0, 938.0)       NaN              1/4      1  <NA>   -1
               [937.0, 938.0)       NaN              1/4      1  <NA>    3
               [937.0, 938.0)       NaN              1/4      1  <NA>   -1
               [937.0, 938.0)       NaN              1/4      1  <NA>    3
               [937.0, 938.0)       NaN              1/4      1  <NA>   -1

                               midi  volta  chord_id tremolo
onset_slice    interval
[0.0, 1.0)     [0.0, 1.0)        53   <NA>        12     NaN
               [0.0, 1.0)        53   <NA>        18     NaN
               [0.0, 1.0)        65   <NA>         0     NaN
               [0.0, 1.0)        65   <NA>         6     NaN
[1.0, 1.5)     [1.0, 1.5)        53   <NA>        13     NaN
...                             ...    ...       ...     ...
[937.0, 938.0) [937.0, 938.0)    53   <NA>      4441     NaN
               [937.0, 938.0)    57   <NA>      4439     NaN
               [937.0, 938.0)    65   <NA>      4439     NaN
               [937.0, 938.0)    69   <NA>      4437     NaN
               [937.0, 938.0)    77   <NA>      4437     NaN

[6857 rows x 19 columns]

In [49]:
salami_notes.loc[("ABC", "n01op18-1_01", pd.Interval(12.0,13.0,closed='left'))]

,quarterbeats,duration_qb,mc,mn,mc_onset,mn_onset,timesig,staff,voice,duration,gracenote,nominal_duration,scalar,tied,tpc,midi,volta,chord_id,tremolo
interval,,,,,,,,,,,,,,,,,,,
"[12.0, 13.0)",12.0,1.0,5,5,0,0,3/4,4,1,3/4,NaN,1/2,3/2,<NA>,2,50,<NA>,64,NaN
"[12.0, 13.0)",12.0,1.0,5,5,0,0,3/4,3,1,3/4,NaN,1/2,3/2,<NA>,2,62,<NA>,63,NaN
"[12.0, 13.0)",12.0,1.0,5,5,0,0,3/4,2,1,3/4,NaN,1/2,3/2,1,-2,70,<NA>,62,NaN
"[12.0, 13.0)",12.0,1.0,5,5,0,0,3/4,1,1,1/4,NaN,1/4,1,1,-1,77,<NA>,56,NaN

In [87]:
chords = chord_slices.get_slice_info().loc[('ABC', 'n01op18-1_01')]
chord0_interval = chords.index[0]
chord0 = chords.loc[chord0_interval]
chord0

quarterbeats                  0
duration_qb                 3.0
mc                            1
mn                            1
mc_onset                      0
mn_onset                      0
timesig                     3/4
staff                         4
voice                         1
volta                      <NA>
harmony_layer                 1
label                       F.I
regex_match                dcml
globalkey                     F
localkey                      I
pedal                       NaN
chord                         I
special                     NaN
numeral                       I
form                        NaN
figbass                     NaN
changes                     NaN
relativeroot                NaN
cadence                     NaN
phraseend                   NaN
chord_type                    M
globalkey_is_minor        False
localkey_is_minor         False
chord_tones           (0, 4, 1)
added_tones                  ()
root                          0
bass_note                     0
alt_label                   NaN
pedalend                    NaN
Name: [0.0, 3.0), dtype: object

In [88]:
salamis = salami_notes.loc[("ABC", "n01op18-1_01")]
salamis[salamis.index.get_level_values(0).overlaps(chord0_interval)]

                        quarterbeats  duration_qb  mc  mn mc_onset mn_onset  \
onset_slice interval
[0.0, 1.0)  [0.0, 1.0)             0         1.00   1   1        0        0
            [0.0, 1.0)             0         1.00   1   1        0        0
            [0.0, 1.0)             0         1.00   1   1        0        0
            [0.0, 1.0)             0         1.00   1   1        0        0
[1.0, 1.5)  [1.0, 1.5)             1         0.50   1   1      1/4      1/4
            [1.0, 1.5)             1         0.50   1   1      1/4      1/4
            [1.0, 1.5)             1         0.50   1   1      1/4      1/4
            [1.0, 1.5)             1         0.50   1   1      1/4      1/4
[1.5, 1.75) [1.5, 1.75)          3/2         0.25   1   1      3/8      3/8
            [1.5, 1.75)          3/2         0.25   1   1      3/8      3/8
            [1.5, 1.75)          3/2         0.25   1   1      3/8      3/8
            [1.5, 1.75)          3/2         0.25   1   1      3/8      3/8
[1.75, 2.0) [1.75, 2.0)          7/4         0.25   1   1     7/16     7/16
            [1.75, 2.0)          7/4         0.25   1   1     7/16     7/16
            [1.75, 2.0)          7/4         0.25   1   1     7/16     7/16
            [1.75, 2.0)          7/4         0.25   1   1     7/16     7/16
[2.0, 2.5)  [2.0, 2.5)             2         0.50   1   1      1/2      1/2
            [2.0, 2.5)             2         0.50   1   1      1/2      1/2
            [2.0, 2.5)             2         0.50   1   1      1/2      1/2
            [2.0, 2.5)             2         0.50   1   1      1/2      1/2
[2.5, 3.0)  [2.5, 3.0)           5/2         0.50   1   1      5/8      5/8
            [2.5, 3.0)           5/2         0.50   1   1      5/8      5/8
            [2.5, 3.0)           5/2         0.50   1   1      5/8      5/8
            [2.5, 3.0)           5/2         0.50   1   1      5/8      5/8

                        timesig  staff  voice duration gracenote  \
onset_slice interval
[0.0, 1.0)  [0.0, 1.0)      3/4      3      1      1/4       NaN
            [0.0, 1.0)      3/4      4      1      1/4       NaN
            [0.0, 1.0)      3/4      1      1      1/4       NaN
            [0.0, 1.0)      3/4      2      1      1/4       NaN
[1.0, 1.5)  [1.0, 1.5)      3/4      3      1      1/8       NaN
            [1.0, 1.5)      3/4      4      1      1/8       NaN
            [1.0, 1.5)      3/4      1      1      1/8       NaN
            [1.0, 1.5)      3/4      2      1      1/8       NaN
[1.5, 1.75) [1.5, 1.75)     3/4      3      1     1/16       NaN
            [1.5, 1.75)     3/4      4      1     1/16       NaN
            [1.5, 1.75)     3/4      1      1     1/16       NaN
            [1.5, 1.75)     3/4      2      1     1/16       NaN
[1.75, 2.0) [1.75, 2.0)     3/4      3      1     1/16       NaN
            [1.75, 2.0)     3/4      4      1     1/16       NaN
            [1.75, 2.0)     3/4      1      1     1/16       NaN
            [1.75, 2.0)     3/4      2      1     1/16       NaN
[2.0, 2.5)  [2.0, 2.5)      3/4      3      1      1/8       NaN
            [2.0, 2.5)      3/4      4      1      1/8       NaN
            [2.0, 2.5)      3/4      1      1      1/8       NaN
            [2.0, 2.5)      3/4      2      1      1/8       NaN
[2.5, 3.0)  [2.5, 3.0)      3/4      3      1      1/8       NaN
            [2.5, 3.0)      3/4      4      1      1/8       NaN
            [2.5, 3.0)      3/4      1      1      1/8       NaN
            [2.5, 3.0)      3/4      2      1      1/8       NaN

                        nominal_duration scalar  tied  tpc  midi  volta  \
onset_slice interval
[0.0, 1.0)  [0.0, 1.0)               1/4      1     1   -1    53   <NA>
            [0.0, 1.0)               1/4      1     1   -1    53   <NA>
            [0.0, 1.0)               1/4      1     1   -1    65   <NA>
            [0.0, 1.0)               1/4      1     1   -1    65   <NA>
[1.0, 1.5)  [1.0, 1.5)               1/8      1    -1   -1    53   <NA>
            [1.0, 1.5)               1/8      1    -1   -1    53   <NA>
            [1.0, 1.5)               1/8      1    -1   -1    65   <NA>
            [1.0, 1.5)               1/8      1    -1   -1    65   <NA>
[1.5, 1.75) [1.5, 1.75)             1/16      1  <NA>    1    55   <NA>
            [1.5, 1.75)             1/16      1  <NA>    1    55   <NA>
            [1.5, 1.75)             1/16      1  <NA>    1    67   <NA>
            [1.5, 1.75)             1/16      1  <NA>    1    67   <NA>
[1.75, 2.0) [1.75, 2.0)             1/16      1  <NA>   -1    53   <NA>
            [1.75, 2.0)             1/16      1  <NA>   -1    53   <NA>
            [1.75, 2.0)             1/16      1  <NA>   -1    65   <NA>
            [1.75, 2.0)             1/16      1  <NA>   -1    65   <NA>
[2.0, 2.5)  [2.0, 2.5)               1/8      1  <NA>    4    52   <NA>
            [2.0, 2.5)               1/8      1  <NA>    4    52   <NA>
            [2.0, 2.5)               1/8      1  <NA>    4    64   <NA>
            [2.0, 2.5)               1/8      1  <NA>    4    64   <NA>
[2.5, 3.0)  [2.5, 3.0)               1/8      1  <NA>   -1    53   <NA>
            [2.5, 3.0)               1/8      1  <NA>   -1    53   <NA>
            [2.5, 3.0)               1/8      1  <NA>   -1    65   <NA>
            [2.5, 3.0)               1/8      1  <NA>   -1    65   <NA>

                         chord_id tremolo
onset_slice interval
[0.0, 1.0)  [0.0, 1.0)         12     NaN
            [0.0, 1.0)         18     NaN
            [0.0, 1.0)          0     NaN
            [0.0, 1.0)          6     NaN
[1.0, 1.5)  [1.0, 1.5)         13     NaN
            [1.0, 1.5)         19     NaN
            [1.0, 1.5)          1     NaN
            [1.0, 1.5)          7     NaN
[1.5, 1.75) [1.5, 1.75)        14     NaN
            [1.5, 1.75)        20     NaN
            [1.5, 1.75)         2     NaN
            [1.5, 1.75)         8     NaN
[1.75, 2.0) [1.75, 2.0)        15     NaN
            [1.75, 2.0)        21     NaN
            [1.75, 2.0)         3     NaN
            [1.75, 2.0)         9     NaN
[2.0, 2.5)  [2.0, 2.5)         16     NaN
            [2.0, 2.5)         22     NaN
            [2.0, 2.5)          4     NaN
            [2.0, 2.5)         10     NaN
[2.5, 3.0)  [2.5, 3.0)         17     NaN
            [2.5, 3.0)         23     NaN
            [2.5, 3.0)          5     NaN
            [2.5, 3.0)         11     NaN

In [47]:
str(pd.Interval(0.0,1.0,closed='left'))

'[0.0, 1.0)'

In [30]:
salami.get_slice_info()

                                     quarterbeats duration_qb   mc   mn  \
corpus fname        onset_slice
ABC    n01op18-1_01 [0.0, 1.0)                  0         1.0    1    1
                    [1.0, 1.5)                  1         0.5    1    1
                    [1.5, 1.75)               3/2        0.25    1    1
                    [1.75, 2.0)               7/4        0.25    1    1
                    [2.0, 2.5)                  2         0.5    1    1
...                                           ...         ...  ...  ...
       n16op135_04  [1140.0, 1141.0)         1140         1.0  281  280
                    [1141.0, 1142.0)         1141         1.0  281  280
                    [1142.0, 1144.0)         1142         2.0  282  281
                    [1144.0, 1146.0)         1144         2.0  282  281
                    [1146.0, 1147.0)         1146         1.0  283  282

                                     mc_onset mn_onset timesig staff voice  \
corpus fname        onset_slice
ABC    n01op18-1_01 [0.0, 1.0)              0        0     3/4     3     1
                    [1.0, 1.5)            1/4      1/4     3/4     3     1
                    [1.5, 1.75)           3/8      3/8     3/4     3     1
                    [1.75, 2.0)          7/16     7/16     3/4     3     1
                    [2.0, 2.5)            1/2      1/2     3/4     3     1
...                                       ...      ...     ...   ...   ...
       n16op135_04  [1140.0, 1141.0)      1/2      1/2     4/4     4     1
                    [1141.0, 1142.0)      3/4      3/4     4/4     4     1
                    [1142.0, 1144.0)        0        0     4/4     4     1
                    [1144.0, 1146.0)      1/2      1/2     4/4     4     1
                    [1146.0, 1147.0)        0        0     4/4     4     1

                                     duration gracenote nominal_duration  \
corpus fname        onset_slice
ABC    n01op18-1_01 [0.0, 1.0)            1/4       NaN              1/4
                    [1.0, 1.5)            1/8       NaN              1/8
                    [1.5, 1.75)          1/16       NaN             1/16
                    [1.75, 2.0)          1/16       NaN             1/16
                    [2.0, 2.5)            1/8       NaN              1/8
...                                       ...       ...              ...
       n16op135_04  [1140.0, 1141.0)      1/4       NaN              1/4
                    [1141.0, 1142.0)      1/4       NaN              1/4
                    [1142.0, 1144.0)      1/2       NaN              1/2
                    [1144.0, 1146.0)      1/2       NaN              1/2
                    [1146.0, 1147.0)      1/4       NaN              1/4

                                     scalar  tied tpc midi volta chord_id  \
corpus fname        onset_slice
ABC    n01op18-1_01 [0.0, 1.0)            1     1  -1   53  <NA>       12
                    [1.0, 1.5)            1    -1  -1   53  <NA>       13
                    [1.5, 1.75)           1  <NA>   1   55  <NA>       14
                    [1.75, 2.0)           1  <NA>  -1   53  <NA>       15
                    [2.0, 2.5)            1  <NA>   4   52  <NA>       16
...                                     ...   ...  ..  ...   ...      ...
       n16op135_04  [1140.0, 1141.0)      1  <NA>  -1   41  <NA>     2719
                    [1141.0, 1142.0)      1  <NA>   3   45  <NA>     2720
                    [1142.0, 1144.0)      1  <NA>   0   48  <NA>     2727
                    [1144.0, 1146.0)      1  <NA>   0   36  <NA>     2728
                    [1146.0, 1147.0)      1  <NA>  -1   41  <NA>     2732

                                     tremolo
corpus fname        onset_slice
ABC    n01op18-1_01 [0.0, 1.0)           NaN
                    [1.0, 1.5)           NaN
                    [1.5, 1.75)          NaN
                    [1.75, 2.0)          NaN
                    [2.0, 2.5)           NaN
...                                      ...
       n16op135_04  [1140.0, 1141.0)     NaN
                    [1141.0, 1142.0)     NaN
                    [1142.0, 1144.0)     NaN
                    [1144.0, 1146.0)     NaN
                    [1146.0, 1147.0)     NaN

[98255 rows x 19 columns]